### ISSUE TITLE
.dataset and aria helper attributes don't disappear if value is null

### ISSUE THREAD

**Issue by Scott-MacD** [WebReflection/lighterhtml#100]
When using the `aria=${{...}}` and `.dataset=${{...}}` properties, the attributes they create don't disappear when given a null value, like other attributes.

As an example, here's a reduced edge case from a node of a tree-view component I'm making.

The following template literal:
```js
html.for(leaf)`
    <li aria=${{expanded: null}} .dataset=${{
        active: true,
        firstNode: null,
        lastNode: null
    }}>
        Hello
    </li>
`
```

results in the following generated html:
```html
<li aria-expanded="null" data-active="true" data-first-node="null" data-last-node="null">
    Hello
</li>
```

Whereas the following template literal:
```js
html.for(leaf)`
    <li aria-expanded=${null}
        data-active=${true}
        data-first-node=${null}
        data-last-node=${null}
    >
        Hello
    </li>
`
```

results in the following generated html:
```html
<li data-active="true">
    Hello
</li>
```

If it's possible to have consistent behavior with setting values to null, it would help cut down on a lot of extra writing for elements with a lot of data attributes and help reduce extra noise. Another specific use case with `aria-expanded` for example, is we only add this attribute at all when a node has any children, if it does, we use the true/false state to decide whether it's open or closed, if not, it should not be present at all. Right now we can't do this with the `aria=${{...}}` attribute and need to add the attribute manually.

**Comment by WebReflection** [comment]
@Scott-MacD fixed, thank you 👋
