### ISSUE TITLE
custom() issues

### ISSUE THREAD

**Issue by MarkChrisLevy** [WebReflection/lighterhtml#101]
I would like to use custom() to transform input html, however it fails with several issues.

Try code below:
```
const {html} = custom({
    attribute: callback => (node, name, original) => {
        console.log(node);
        return callback(node, name, original);
    }
});

const expr = true;
console.log(html.node`<if expr=${expr}><div>test</div></if>`);
```

When executed an error is thrown:
*TypeError: Cannot read property 'type' of undefined*

Also, I there is a problem with TypeScript type def - when I try to override transform I get following TypeScript error:
`TS2345: Argument of type '{ attribute: (callback: (...args: any) => (value: any) => void) => (node: any, name: any, original: any) => (value: any) => void; transform(transform: (markup: string) => string): (markup: string) => string; }' is not assignable to parameter of type '{ convert?(stringify: (template: TemplateStringsArray) => string): (template: TemplateStringsArray) => string; transform?(transform: (markup: string) => string): (markup: string) => string; } & { ...; }'.   Type '{ attribute: (callback: (...args: any) => (value: any) => void) => (node: any, name: any, original: any) => (value: any) => void; transform(transform: (markup: string) => string): (markup: string) => string; }' is not assignable to type '{ [override: string]: (defaultConversion: (...args: any) => (value: any) => void) => (...args: any) => (value: any) => void; }'.     Property 'transform' is incompatible with index signature.       Types of parameters 'transform' and 'defaultConversion' are incompatible.         Type '(value: any) => void' is not assignable to type 'string'.`

**Comment by WebReflection** [comment]
I don't use TypeScript, so if there's anything you'd like to fix, please send a PR.

Regarding custom, it's used heavily in [heresy](https://github.com/WebReflection/heresy/blob/master/esm/augmented.js#L32-L38), maybe you can find [how it's done in there](https://github.com/WebReflection/heresy/blob/d09af7bd9e01c1d44d75eff79b07634403081792/index.js#L1778)?
