### ISSUE TITLE
Spurious error message "Error: <svg> attribute width: A negative value is not valid." when rendering a SVG icon

### ISSUE THREAD

**Issue by appletomato** [WebReflection/lighterhtml#103]
I am using lighterhtml to render a SVG icon like in the following snippet:

```ts
import { render, html, svg } from 'lighterhtml'

const aProps = {
  width: "48",
  height: "48",
  fill: "red",
  class: "svg-icon",
  viewBox: "0 0 24 24",
  path: "M19.43 12.98c.04-.32.07-.64.07-.98s-.03-.66-.07-.98l2.11-1.65c.19-.15.24-.42.12-.64l-2-3.46c-.12-.22-.39-.3-.61-.22l-2.49 1c-.52-.4-1.08-.73-1.69-.98l-.38-2.65C14.46 2.18 14.25 2 14 2h-4c-.25 0-.46.18-.49.42l-.38 2.65c-.61.25-1.17.59-1.69.98l-2.49-1c-.23-.09-.49 0-.61.22l-2 3.46c-.13.22-.07.49.12.64l2.11 1.65c-.04.32-.07.65-.07.98s.03.66.07.98l-2.11 1.65c-.19.15-.24.42-.12.64l2 3.46c.12.22.39.3.61.22l2.49-1c.52.4 1.08.73 1.69.98l.38 2.65c.03.24.24.42.49.42h4c.25 0 .46-.18.49-.42l.38-2.65c.61-.25 1.17-.59 1.69-.98l2.49 1c.23.09.49 0 .61-.22l2-3.46c.12-.22.07-.49-.12-.64l-2.11-1.65zM12 15.5c-1.93 0-3.5-1.57-3.5-3.5s1.57-3.5 3.5-3.5 3.5 1.57 3.5 3.5-1.57 3.5-3.5 3.5z"
}

const aSvgIcon = (theProps: typeof aProps) => svg`
  <svg 
    width="${theProps.width}" 
    height="${theProps.height}" 
    fill="${theProps.fill}" 
    class="${theProps.class}" 
    viewBox="${theProps.viewBox}">
      <path d="${theProps.path}"/>
  </svg>
`

render(document.body, () => aSvgIcon(aProps))
```

The SVG icon renders fine, but in the web console I obtain error messages like `Error: <svg> attribute width: A negative value is not valid.`, see screenshot. What is wrong with my code or is this a bug with lighterhtml? 

![Screenshot 2021-04-09 at 03 00 17](https://user-images.githubusercontent.com/20613332/114113784-c549a900-98df-11eb-95a6-e13df1ed9005.png)

I have also tried to use lighterhtml's `html` method instead of `svg` but in this scenario the SVG icon is not rendered at all and the error `tagger.js:22 Uncaught TypeError: Cannot set property width of #<SVGSVGElement> which has only a getter` is thrown.

**Comment by appletomato** [comment]
Ok, in the meantime I have noticed that the error message is the same as in [Issue 67](https://github.com/WebReflection/lighterhtml/issues/67) but out of curiosity, I would like to know why the code fails when `html` instead of `svg` is used:

```ts
// this does not work
const aSvgIcon = (theProps: typeof aProps) => html`
  <svg 
    width="${theProps.width}" 
    height="${theProps.height}" 
    fill="${theProps.fill}" 
    class="${theProps.class}" 
    viewBox="${theProps.viewBox}">
      <path d="${theProps.path}"/>
  </svg>
```

**Comment by WebReflection** [comment]
This is [the same bug](https://bugs.chromium.org/p/chromium/issues/detail?id=703588) and the plot twist is that those errors are not real errors, the code runs just fine, the browser throws an error without stopping execution, instead of warning about invalid values (which they are fixing, have fixed).

There's nothing I can do about it, but if you want to stop seeing this error, please consider [µhtml](https://github.com/WebReflection/uhtml#readme) instead, as the template parsing is different, and none of these errors will ever been shown.
