### ISSUE TITLE
How do I insert unsafe html? 

### ISSUE THREAD

**Issue by rajasimon** [WebReflection/lighterhtml#105]
I wanted to include html that comes from the props. For example there is blog post with content but the content is in the html_content

```
export default function listArticle(article) {
  const blogstreakEmbed = document.getElementById("blogstreakEmbed");
  render(
    blogstreakEmbed,
    html`
      <div class="article-detail">
        <h1 class="article-title">${article.title}</h1>
        <div class="article-content" id="article-content">
          ${article.html_content}
        </div>
      </div>
    `
  );
}
```
But all I can see is html content displayed in as string instead of the html 

<img width="1023" alt="image" src="https://user-images.githubusercontent.com/6974101/207291391-713c9c2d-bdf4-4b2f-b50d-574e296061cd.png">

Now I searched online and found lit.dev has [unsafehtml](https://lit.dev/docs/templates/directives/#unsafehtml) and that is exactly I wanted to do it in with lighterhtml. 

Is there any alternative way I can make it work? I also tried with `uhtml-itents` but I can't make it work. 

i.e)

```
import { define, intent } from "uhtml-intents";

define("unsafe", (HTML) => html([HTML]));

export default function listArticle(article) {
    -- rest of the code --
    <div class="article-content" id="article-content">
      ${intent({ unsafe: article.html_content })}
    </div>
}
```

**Comment by yuretz** [comment]
[How about this?](https://jsfiddle.net/yuretz/5zpk26Ls/)

**Comment by rajasimon** [comment]
Thanks @yuretz  Nice and simply get the job done 🎉

**Comment by WebReflection** [comment]
> I also tried with uhtml-itents but I can't make it work.

uhtml and lighterhtml are two different projects ... I don't think uhtml-intents are meant to work with lighterhtml but the code, theoretically, was right (for uhtml)
