### ISSUE TITLE
Consider capitalising “HTML” in the title

### ISSUE THREAD

**Issue by ExE-Boss** [WebReflection/lighterhtml#18]
Right now, lighterHTML is capitalised as “lighterhtml”.

Since it’s meant to be a successor to hyperHTML, I suggest capitalising it as “lighterHTML”.

---

Steps to change capitalisation:
1. Go to [repository settings](https://github.com/WebReflection/lighterHTML/settings).
2. Change the repository name to&nbsp;something else (e.g.:&nbsp;“lighterHTML-temp”), this is&nbsp;because GutHub doesn’t support changing just the&nbsp;repository name’s&nbsp;case).
3. Change the&nbsp;repository name to&nbsp;“lighterHTML”.

**Comment by WebReflection** [comment]
Not the successor, it reflects it's npm name.

This one is a won't change, sorry
