### ISSUE TITLE
readme code pen not launching

### ISSUE THREAD

**Issue by thipages** [WebReflection/lighterhtml#2]
Hi,
you may have seen it since you are updating.
In case of...

**Comment by mxcoder** [comment]
Just to be clear @WebReflection , the problem is that `https://unpkg.com/lighterhtml@0.3.3/esm/index.js?module` is being bundled with:
```
import tta from "http://localhost:5000/@ungap/template-tag-arguments@^0.1.1?module";
```
At the first line, Andrea stated in twitter that seems to be an unpkg bug :(
