### ISSUE TITLE
SVG 

### ISSUE THREAD

**Issue by ripter** [WebReflection/lighterhtml#21]
Page that shows the issue (open in a debug view so you can see the console log): https://codepen.io/ripter/pen/WmNRJM?editors=1010

The error: 
> index.js?module:49 Error: <polygon> attribute points: Expected number, "-0.685321%".

Example Code:
```
render(document.querySelector('svg .polygons'), 
       () => svg`<polygon points=${[0, 0, 0, 56, 100, 56]}></polygon>`);
```

**Comment by WebReflection** [comment]
Does it work?

**Comment by ripter** [comment]
It renders the first time, but when I try to change the points and render an update, the svg still shows the old values.

**Comment by WebReflection** [comment]
Browsers are loud about SVG attributes, but that can be safely ignored as it's been for hyperHTML for years now.

So, unless you show me your code that shows a real issue with this library, there's not much I can do.

Also, arrays as attributes are not really a valid value, try to join to pass along a string instead

**Comment by ripter** [comment]
I updated the example. If I add the `.join(',')` to the array, it works and only throws that error once.

**Comment by WebReflection** [comment]
admittedly arrays could be joined automatically, 'cause while this would need `,`, classes would need ` ` so there's no easy way to know upfront the kind of string the attribute expects
