### ISSUE TITLE
Question: isomorphic support?

### ISSUE THREAD

**Issue by bstro** [WebReflection/lighterhtml#24]
Hi there, I'm a bit new to all this, but am wondering, does `lighterhtml` support building isometric apps? Maybe a `renderToString` method? Haven't seen anything like this so far, but this lib looks cool as hell and I'd love to use it in this way.

**Comment by bstro** [comment]
@joshgillies Thanks! Hah, yeah, I meant isomorphic (been dabbling in pixelart lately so the brain wires got crossed).

**Comment by joshgillies** [comment]
Haha, no worries! I hope `basicHTML` works out for you. Do report back if there are any issues. 👍

**Comment by WebReflection** [comment]
you can use [viperHTML](https://github.com/WebReflection/viperHTML#viperhtml) for server side rendering.

```js
const {bind, wire} = require('viperhtml');
const html = (...args) => wire()(...args);
```

it want be 1:1 API experience like it would with hyperHTML but it should be fine to play around with that.
