### ISSUE TITLE
How to set / clear custom boolean attribute?

### ISSUE THREAD

**Issue by ludmiloff** [WebReflection/lighterhtml#27]
Currently I cannot set/clear custom boolean attribute as stated in the hyperHTML docs.
It is only possible with a workaround IMO however, see the example code here:

```
import { html, render } from "lighterhtml";

document.body.appendChild(
  html`
    <div id="example1" top="${true}">
      set custom attribute top (wrong top="true")
    </div>
    <div id="example2" top="${false}">
      clear custom attribute top (wrong top="false")
    </div>
    <div id="example3" top="${!true ? undefined : ""}">
      clear custom attribute top (working)"
    </div>
    <div id="example4">
      Different behaviour for well known attributes <br />
      <button disabled="${true}">Disabled button</button>
      <button disabled="${false}">Enabled button</button>
    </div>
  `
);
```

A link to codesanbox:
[boolean attribute example](https://codesandbox.io/embed/xzr9p3vkmp)

An intended behaviour or my bad understanding of documentation?
Sorry this might be related or duplicate of #19

**Comment by WebReflection** [comment]
`top` is not a boolean attribute ... boolean attributes are those defined by specs as such, like `button.disabled` and similar.

to drop attributes that are not standard, use `null` or be are, whatever thing you pass will be set as string, even an empty one.

I also suggest to **not** use non standard attributes, you have both custom elements, and `data-` attributes for that.
