### ISSUE TITLE
how should I use i18n-node with lighterhtml? [help]

### ISSUE THREAD

**Issue by kxrom** [WebReflection/lighterhtml#31]
About [i18n-node](https://github.com/mashpie/i18n-node), where should I register `__()` to be used within lighterhtml templates?

This is an example implementation for handlebarsjs.com template engine:
```js
// register hbs helpers in res.locals' context which provides this.locale
hbs.registerHelper('__', function () {
  return i18n.__.apply(this, arguments);
});
hbs.registerHelper('__n', function () {
  return i18n.__n.apply(this, arguments);
});

```

**Comment by WebReflection** [comment]
lighterhtml is not compatible with node (meaning: it doesn't do SSR)

to use `i18n` with anything, just use it normally

```js
html`<div>${i18n`my content`}</div>`
```
