### ISSUE TITLE
Big thanks and advice about SSR (server side render)

### ISSUE THREAD

**Issue by alexey13** [WebReflection/lighterhtml#33]
Good day, Andrea! Want to say why using lighterHtml and love it. I always start from basics. First,  made a project using js native template literals. But the whole component rerender every time (main cons for me) so started to search something like dom diff. I knew about react, angular, vue but i dont want to use something very complicated. I want to control and understand as much as i can what really library do. For me react and others do too much. There is just no control for me. Why i should use them if lighterhtml is smaller, render views faster, every event in control. Nested components - no problem. I dont use Classes and now dont understand why they are better (maybe my skills just not so good or project not so big to use components based on Classes or maybe not). Structure of my component. Want to share with you and others:
```
const component = (function() {
const state = {
  something: '',
  array: []
};
const actions = {
  mutateState: (e) => {
    state.something = e.currentTarget.value;
    renderComponent();
  }
};
const htmlMain = state => html`
  <input oninput=${actions.mutateState} type="text" placeholder="" value=${state.something}>
`;
const renderComponent = () => {
  const container = document.getElementById('element');
  render(container, () => htmlMain(state));
};
return {
  actions: actions
};
})();
```
I cant see any cons in this for now. I have tried nested component and it works like a charm.

Now i tnink more and more about SSR. Main cons of clientside render is SEO. Without SSR it going to be low. Only google can crowl data that fetched in clientside websites. I saw viperHtml, basicHtml but its a lack of examples and documentation. I know about prerender.io and maybe it good for a start, but in future want to control as much as i can. And my knoweldge of NodeJs and Express is 0 now. I saw hackerNews example its good one.
What roadmap would you recommend to make my project SSR? From basics to complicated. Almost always i using examples and documentation as the starting point. HackerNews example based on viperHtml best choice?

**Comment by WebReflection** [comment]
@alexey13 apologies for the late answer, but I'm planning to release lighterssr too, so you can create pages on the server side, similarly to how you do on the client.

Unfortunately, I am lacking free time these days, so I cannot say when this will happen.

Meanwhile, please have a look at viperHTML, which should really not be too difficult to grasp.
