### ISSUE TITLE
Bundler Warning

### ISSUE THREAD

**Issue by robhicks** [WebReflection/lighterhtml#37]
I'm using lighterhtml with an app bundled with Rollup.

Rollup emits the following warning when building:

```
(!) `this` has been rewritten to `undefined`
https://rollupjs.org/guide/en#error-this-is-undefined
node_modules/@ungap/weakmap/esm/index.js
1: /*! (c) Andrea Giammarchi - ISC */
2: var self = this || /* istanbul ignore next */ {};
              ^
3: try { self.WeakMap = WeakMap; }
4: catch (WeakMap) {
```

**Comment by WebReflection** [comment]
lighterhtml is bundled with rollup itself, all you need is:
https://github.com/WebReflection/lighterhtml/blob/master/rollup.config.js#L12-L13

those are irrelevant warnings needed for polyfills, with those changes in you won't see any warning.
