### ISSUE TITLE
About the name ... again ;-)

### ISSUE THREAD

**Issue by thipages** [WebReflection/lighterhtml#4]
Hi,

name is identity, personal and communitary.
It can be short, nice to hear or evocating something people are ready  to/will share, it can be technical.

Writing it in two words lighter-html and it may end as lighter.
It could be concord, weal, fare, fair. (I was thinking first fit but already taken)

Just thoughts, no issue :  I am closing right away.

**Comment by WebReflection** [comment]
> (I was thinking first fit but already taken)

which is why this is called as such
