### ISSUE TITLE
html.for Failed to execute 'insertBefore' on 'Node'

### ISSUE THREAD

**Issue by vdzk** [WebReflection/lighterhtml#48]
html.for breaks when I try to reorder nodes. I've prepared another test case to showcase this + [codepen](https://codepen.io/anon/pen/bPdOoM?editors=0010).
```javascript
const {render, html} = lighterhtml

const list1 = [
  {id: 1, desc: 'apple', priority: 1},
  {id: 2, desc: 'banana', priority: 2},
  {id: 3, desc: 'orange', priority: 3},
]

const list2 = [
  {id: 1, desc: 'apple', priority: 1},
  {id: 2, desc: 'banana', priority: 2},
  {id: 3, desc: 'orange', priority: 3},
]

const byPriority = (a, b) => b.priority - a.priority

list1.sort(byPriority)
list2.sort(byPriority)

const increase = (list, item) => () => {
  item.priority += 1
  list.sort(byPriority)
  update()
}

const decrease = (list, item) => () => {
  item.priority -= 1
  list.sort(byPriority)
  update()
}


const Button = (text, onClick) => html`
  <button onclick=${onClick}>
    ${text}
  </button>
`

const ListItem = (item) => html`
  <li>
    ${Button('▲', increase(list1, item))}
    P:${item.priority}
    ${Button('▼', decrease(list1, item))}
    ${item.desc}
  </li>
`

const ListForItem = (item) => html.for(item, ':li')`
  <li>
    ${Button('▲', increase(list2, item))}
    P:${item.priority}
    ${Button('▼', decrease(list2, item))}
    ${item.desc}
  </li>
`

const Lists = () => html`
  <ul>
    ${list1.map(ListItem)}
  </ul>
  <ul>
    ${list2.map(ListForItem)}
  </ul>
`

const update = () => {
  render(document.body, () => Lists())
}

update()
```
Steps to reproduce: In the second list (rendered with html.for) click on the down arrow of the first (orange) item twice.
Expected result: the item (orange) moves down like in the first list.
Observed result: the item doesn't move, buttons disappear, console shows "Uncaught DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.".

**Comment by WebReflection** [comment]
Another nice bug to fix for me, thank you.

Latest version should work just fine, there was indeed a too naive logic implemented for wired content, but now everything should be fine.

Please do let me know if not 👋

**Comment by vdzk** [comment]
The latest version fixed html.for for my app.
Thanks a lot!

**Comment by WebReflection** [comment]
You are more than welcome 👋
