### ISSUE TITLE
Wrong <select> option is selected 

### ISSUE THREAD

**Issue by yuretz** [WebReflection/lighterhtml#58]
As demonstrated [by this small example](https://jsfiddle.net/yuretz/y821dL7k/), dynamically generated `select` seems to select the wrong item if options are rendered in two pieces. It's not difficult to work around, but it's weird anyway.

This could have something to do with #50 but I'm not sure, therefore I created this as a separate issue.

**Comment by WebReflection** [comment]
> It's not difficult to work around

actually curious to know the use case for creating selects like that 🤔

I'll try to figure out if this affects hyperHTML too and, if it does, I'll try to find a solution. However, since I believe this is a browser issue with selects and options, I'm not sure there's much I can do.

If that'd be the case, I'll put a caveat with selects in the doc/readme and flag this as won't fix.

Meanwhile it's deadly easy to work-around the issue, so I hope you're not stuck because of this way to create selects.

**Comment by yuretz** [comment]
> actually curious to know the use case for creating selects like that 🤔

Well it was just a dirty/silly way to insert a default `<option>`  in a select, like
```javascript
const select = (items) => html`
	<select>
		${option(defaultItem)}
		${items.map(option)}
	</select>
`;

const option = (item) = html`<option>...bla bla bla...</option>`;
```
> Meanwhile it's deadly easy to work-around the issue, so I hope you're not stuck because of this way to create selects.

No problem at all, `[defaultItem, ...items].map(option)` solves it nicely enough, I think 😄

**Comment by yuretz** [comment]
> I believe this is a browser issue with selects and options, I'm not sure there's much I can do.

Well, it behaves the same way in Chrome, Edge and Firefox. Are they all doing it wrong?

I generally agree, that this way of composing select options looks odd/ugly, but at the same time it is extremely non obvious for me, as a user, why should a simple code like this fail, unless lighterhtml has a built-in aesthetic detector 😉. 

In my experience, issues like this are often an indication that something fishy is going on under the surface.

**Comment by WebReflection** [comment]
To rephrase, this is a low priority for me, as the use case to split options is not common, and I've a lot on my plate right now, so I hope you can survive in the meanwhile with the workaround

**Comment by WebReflection** [comment]
P.S. of course, PR welcome

**Comment by yuretz** [comment]
Clear, thanks. I'll try to find some time to look at it during the weekend.

**Comment by WebReflection** [comment]
interesting bug, and it was affecting hyperHTML too (domdiff issue)

It's fixed now, thanks.
