### ISSUE TITLE
[Question] Best practice for CE slotted content w/o shadow DOM

### ISSUE THREAD

**Issue by matsp** [WebReflection/lighterhtml#59]
I would like to use lighterhtml for custom elements. They should render on their own. Further I want to declaratively define children in my markup that should be rendered in "slots".

I don't want to use shadow DOM because it's limiting me by scoping CSS... So what I really need is the composition of shadow DOM with shared CSS. That's actually not possible with actual browser implementations / specifications.

In this [codepen](https://codepen.io/matsp/pen/RwbadbK) lighterhtml is rendering at the root of the custom element - this removes declared children.
With manual work I can clone and reinsert children but that isn't very transparent.

I would like to have this output:

```html
<h1>hello</h1>
<p>some text</p>
```

Do you have an idea to archive markup composition without shadow DOM with lighterhtml?

Thanks in advance!

**Comment by WebReflection** [comment]
You don't even need the slot, as long as you trap once the initial content in the constructor, as shown here: https://codepen.io/WebReflection/pen/wvwGZjv?editors=0010

**Comment by matsp** [comment]
Great! I like the simplicity:blush:

**Comment by WebReflection** [comment]
Just please bear in mind Custom Elements upgrades are "funny" ... so that you might want to use [HTMLParsedElement](https://github.com/WebReflection/html-parsed-element) base constructor, instead of `HTMLElement`, and do that very same dance within the `parsedCallback` method.
