### ISSUE TITLE
Extend Tagger's attribute

### ISSUE THREAD

**Issue by vuhg** [WebReflection/lighterhtml#60]
Hello Andrea Giammarchi,

Please export `Tagger` or allow dev to extend its `attribute` method.
I like to make custom attributes or directives, for example:
```javascript
html`
  <div class:red=${isAlert} transition=${fade}>
    ${ message }
  </div>
`
```

Solution: 
1. (Prefer)
```javascript
import { transformAttribute } from 'lighterhtml'

transformAttribute((node, name, original) => {
  // do cool stuff
}
```
2.
```javascript
// in case someone want to do more things with Tagger's internal
import { Tagger } from 'lighterhtml'

const taggerAttribute = Tagger.prototype.attribute
Tagger.prototype.attribute = (node, name, original) => {
  // do cool stuff
  return taggerAttribute(node, name, original)
}
```

Many thanks,
vuhg

**Comment by WebReflection** [comment]
The second option won't happen for at least two reasons:

  1. you are polluting the prototype for every other part of the project that might use lighterhtml too
  2. you cannot possibly use an arrow function as prototype method, like ever, 'cause you need the context, so that virtually breaks already

The only way I could think of offering the functionality is to export an `override({...})` method that won't expose the Tagger directly but lets you do whatever you want with `attribute`, `text`, or `any` ... although, that's complicated as it is for the current core.

Accordingly, I'd love to understand what is it that you cannot really do already, since you are the one defining template literal and its holes content, so I am nut sure this request is worth the effort needed to make it possible (specially after years on hyperHTML where this was never needed).

Can you please show exact use case of what you are trying to do or what you are expecting? Also please consider having a callback as hole, within the node, lets you do whatever you want with it too.


```js
const doStuff = node => {
  if (node.hasAttribute('class:red')) {
    // do things
  }
  return message;
};
html`
  <div class:red transition=${fade}>
    ${doStuff}
  </div>
`
```

**Comment by vuhg** [comment]
`override` wound be cool too.

I want to build an UI library on top of lighterhtml that support directives 
like multiple class/style binding, show, animation, transition, ...
For example:
```javascript
html`
  <div class:inactive=${!isActive} class:admin=${isAdmin} transition=${fade}>
  
  </div>
`
```

```javascript
const PhoneInput = ({ initialValue, inputCb, country, customStyle }) =>
html`
  <input 
    class:dark=${theme.isDark} 
    style="width: 100%;"
    style=${customStyle}
    type="text" 
    use:phoneFilter=${country.pattern}
  >
`
```

Like `input` case, i can't see how callback will help.

**Comment by WebReflection** [comment]
OK, I see your point. I need to think about it, 'cause also the override is not too trivial.

```js
const {html, svg} = override({attribute: fn => (node, name, original) => {
  if (name === 'class:red')
    return whatDoYouDoHere('???');
  return fn(node, name, original);
}});
```

For your use case, I see that a helper might be a not too bad workaround:
```js
const phoneFilter = (node) => (pattern) => {
  // subscribe to keypress
  return () => {
    // cleanup: unsubscribe to keypress 
  }
}

const nc = object => Object.keys(object).reduce(
  (c, k) => object[k] ? (c + ' ' + k) : '', '
').slice(1);

const PhoneInput = ({ initialValue, inputCb, country, customStyle }) =>
html`
  <input 
    class=$(nc({dark: theme.isDark}))
    style=${customStyle}
    type="text"
    filter=${country.pattern}
    value=${initialValue}
    oninput=${inputCb}
  >
`
```

Also please note using same attribute name twice won't work, as you did with `style` in your example

**Comment by vuhg** [comment]
Could we have something like this, i take from `transform`:
```javascript
// an indirect exposure of a domtagger capability
// to extend attributes
export const overrideAttribute = callback => {
  const { attribute } = Tagger.prototype;
  Tagger.prototype.attribute = function (node, name, original) {
    const isHandled = callback(node, name, original);
    if (isHandled) return;
    attribute(node, name, original);
  }
};
```

**Comment by WebReflection** [comment]
the transform works with the string and it needs to return one ... doing that might be an option but I'm not too happy about current transform myself, due tagger pollution, so this might be an occasion to have a better solution that works with others too.

**Comment by WebReflection** [comment]
P.S. the transform is needed for [heresy](https://github.com/WebReflection/heresy/#-heresy-), based on this project too, and in _heresy_ you can do already whatever you like 'cause you define on the component any attribute you like and behave accordingly

**Comment by vuhg** [comment]
Thank you for considering it.
Please take your time.

I come from lit-element and lit-html and i found `lighterhtml` much simpler to work with.
I've looked at `heresy` but it doesn't suit my need at the moment.

**Comment by WebReflection** [comment]
Could you please check these instructions https://github.com/WebReflection/lighterhtml/tree/custom-tagger#v1-changes--new-feature and give this file a try ? https://raw.githubusercontent.com/WebReflection/lighterhtml/custom-tagger/es.js

you should simply include and use `const { html, render } = lighterhtml.custom({...})` to test your use case.

The branch seems to work already in heresy so I'm pretty happy with the result.

Please let me know if something is not clear, thanks.

**Comment by vuhg** [comment]
WOW! So fast, man! Can't thank you enough.

Yeah, I'm happy with the result, too.

I see there is unused `any` in (the second one) in the document of custom-tagger branch:
```any: callback => any(node, childNodes) => {```

Respect,
vuhg

**Comment by WebReflection** [comment]
thanks for the quick review, I've fixed already the index thing and publishing v1 now.

**Comment by WebReflection** [comment]
V1 published with those changes in
