### ISSUE TITLE
SVG dynamic width/height shows console errors (chrome)

### ISSUE THREAD

**Issue by thipages** [WebReflection/lighterhtml#67]
Hi,
the following code WORKS but shows errors in chrome console (not firefox)
there is no console errors when replacing width/height values by the static values.

```javascript
const test=(size)=> {
    const size80=size*0.8;
    const size10=size*0.1;
    return svg`
        <svg  width=${size} height=${size}  style="border:solid">
            <rect x=${size10} y=${size10} width=${size80} height=${size80} />
        </svg>`;
};
render(document.body),()=>test(100));
```
![image](https://user-images.githubusercontent.com/130309/67670760-e0875980-f974-11e9-9fb4-67b66cb8effa.png)

**Comment by WebReflection** [comment]
You can ignore those, as it's a browser issue I've filed already, and there's nothing I can do.

**Comment by WebReflection** [comment]
P.S. the browser issue is that it shows errors instead of, if really needed, warnings, but the SVG works as meant, so no worries, all is fine
