### ISSUE TITLE
Textarea contents are not updated on screen

### ISSUE THREAD

**Issue by dante-ga** [WebReflection/lighterhtml#68]
Hello,

Here is a codepen showing the issue: https://codepen.io/dante_diagram/pen/KKKyQmb?editors=0010

If you type something in the textarea and click "clear" it doesn't clear (in FF and Chrome). 
Additionally, cursor disappears after typing a couple of character and needs to be reset manually (in Chrome).

Am I doing this wrong?

If this a browser issue, please suggest a workaround.

Thanks!

**Comment by WebReflection** [comment]
The textarea content is accessible via `value` attribute, not through its text node content.

If you try this instead, it'll work as expected:

```js
<textarea oninput=${updateText} value=${text}/>
```

note the difference: the `text` is the `value`, not its child
