### ISSUE TITLE
Composition of components

### ISSUE THREAD

**Issue by thipages** [WebReflection/lighterhtml#7]
Hi,
I would like to nest components in component. Simple example:
```
const textarea= () => html`</textarea>`;
const title= (name) => html`<div>${name}</div>`;
const layout = ()=>html`
     <div> /** placeholder1 */ </div>
     <div> /** placeholder2 */ </div>
`;
render(document.body, () => layout);
```
How can I feed layout with the two above components?

If I should ask it elsewhere, tell me.

**Comment by WebReflection** [comment]
not sure I understand the question but wouldn't this just work?

```js
const textarea= () => html`<textarea />`;
const title= (name) => html`<div>${name}</div>`;
const layout = ()=>html`
     <div> ${title} </div>
     <div> ${textarea} </div>
`;
render(document.body, () => layout);
```

**Comment by WebReflection** [comment]
sorry, I've updated the example

**Comment by WebReflection** [comment]
ok, updated the example with working / tested code. There were few typos in yours, now that's OK.

**Comment by WebReflection** [comment]
P.S. in case you'd like to know how to compose multiple components:

```js
const textarea= () => html`<textarea />`;
const title= (name) => html`<div>${name}</div>`;
const layout = (name) => html`
     <div> ${title(name)} </div>
     <div> ${textarea()} </div>
`;

const divs = [
  // either through other renders
  render(
    document.createElement('div'),
    () => layout('first')
  ),
  render(
    document.createElement('div'),
    () => layout('second')
  ),
  // or directly through other html invokes
  layout('third'),
  layout('fourth')
];

render(document.body, () => html`${divs}`);
```

**Comment by thipages** [comment]
Thanks! Thats good to see another ways to manage things.

I was more looking for having `layout` with `title` and `textearea` as arguments in order to have a more generic layout that can manage other components as well.

**Comment by WebReflection** [comment]
you need to invoke it ... `textarea()` ... you gotta return `html` or nothing happens

**Comment by WebReflection** [comment]
also no need to html`${component(}` if component already returns `html` ;-)

```js
const textarea= () => html`<textarea />`;
const title= (name) => html`<div>${name}</div>`;
const layout = (comp1,comp2) => html`
     <div> ${comp1} </div>
     <div> ${comp2} </div>
`;
render(document.body, () => layout(
  title("Andrea"),
  textarea()
));
```

got it?

**Comment by thipages** [comment]
Yes, got them both thank you. 

A last for this thread:

Is it a "good" way to go to call `render(document.body, layoutFunction);` while layout may carry all application components?
```javascript
import {render, html} from '//unpkg.com/lighterhtml?module';
const textarea= () => html`<textarea />`;
const title= (name) => html`<div>${name}</div>`;
const layout = (comp1,comp2) => html`
     <div> ${comp1} </div>
     <div> ${comp2} </div>
`;

// simulates external state management
setInterval(function() {
  let name="Andrea "+Math.random();
  render(document.body, () => layout(
    title(name),
    textarea()
  ));
},1000);
```

**Comment by WebReflection** [comment]
> while layout may carry all application components?

not sure I understand the question but the example looks fine to me

**Comment by thipages** [comment]
oops.
Imagine that the layout have a header, footer and a main area ... even left/right panes
All these areas may have many components and states.

Each time something change, I may call 

```javascript
function callFirstAndWhenStateChanges() {
   render(document.body, () => layout(
       header (headerNestedComponents),
       main (mainNestedComponents(otherNestedComponents()),
       footer (footerNestedComponents)
     ));
}
```
Is it ok to manage states like this?

If still not clear, dont worry, I will build an example to illustrate it.
