### ISSUE TITLE
Uncaught DOMException: Failed to execute 'insertBefore' on 'Node'

### ISSUE THREAD

**Issue by AllNamesRTaken** [WebReflection/lighterhtml#71]
I am building a TreeView component for fun and ran into this bug which is very similar to one bug solved in June.

The error happens when I remove a branch of my tree and try to place it higher up in the tree hirarchy.
The error I get is:

utils.js:9 Uncaught DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at append (http://localhost:1234/src.77de5100.js:2764:12)
    at domdiff (http://localhost:1234/src.77de5100.js:3148:23)
    at Object.anyContent [as fn] (http://localhost:1234/src.77de5100.js:3889:53)
    at http://localhost:1234/src.77de5100.js:3525:25
    at http://localhost:1234/src.77de5100.js:3554:21
    at unroll (http://localhost:1234/src.77de5100.js:4176:11)
    at unrollArray (http://localhost:1234/src.77de5100.js:4200:18)
    at unroll (http://localhost:1234/src.77de5100.js:4163:3)
    at Object.update (http://localhost:1234/src.77de5100.js:4127:20)
    at Object.render (http://localhost:1234/src.77de5100.js:4003:28)

append | @ | utils.js:9
  | domdiff | @ | index.js:155
  | anyContent | @ | tagger.js:232
  | (anonymous) | @ | index.js:82
  | (anonymous) | @ | index.js:109
  | unroll | @ | index.js:189
  | unrollArray | @ | index.js:210
  | unroll | @ | index.js:184
  | update | @ | index.js:158
  | render | @ | index.js:30
  | render | @ | TreeView.ts:33
  | (anonymous) | @ | TreeView.ts:27

I tried to reproduce using a simpler setup but failed.
I will try and reproduce when I am more awake.

**Comment by AllNamesRTaken** [comment]
Code to reproduce:
```typescript
import { html, render } from "lighterhtml";

type Kind = "frame" | "control";
const NOT_SET = "NOT SET";
export interface NodeData<K> {
  kind: K;
}
export interface ITree<T> {
  id: string;
  data: T;
  children: ITree<T>[] | null;
}
interface ITreeConfig<T> {
  id: string;
  target?: HTMLElement;
  tree: ITree<T>;
}
export class SimpleTreeView<T extends NodeData<K>, K = any> {
  private id: string;
  public tree: ITree<T>;
  private target: HTMLElement | null = null;

  constructor({ id, target, tree }: ITreeConfig<T>) {
    this.id = id;
    this.target = target || null;
    this.tree = tree;
  }

  public render(target?: HTMLElement | null) {
    target 
      && (this.target = target);
    this.target 
      && !(this.target as any).context 
      && ((this.target as any).context = this);

    return this.target && render(this.target, () => html`
    <div id=${this.id} class="tree">
      ${this.tree && renderTreeNodeView(this.tree)}
    </div>
    `);
  }
}

function renderTreeNodeView<T extends NodeData<K>, K = any>(subtree: ITree<T>): HTMLElement {
  let children = subtree.children;
  console.log("render node " + subtree.id)
  let childViews = children && children!.map((c) => {
    return renderTreeNodeView(c);
  });
  return html`
  <div class="treenode">
      <span>${subtree.id}${subtree.data!.kind}</span>
      ${childViews}
  </div>
  `;
}

type MyKind = "frame" | "button";
interface ITreeData { id: string, parent: string | null, data: { kind: MyKind } };
function createTree() {
    let treeData = [
        { id: "root", parent: null, data: { kind: "frame" as MyKind } },
        { id: "n1", parent: "root", data: { kind: "frame" as MyKind } },
        { id: "n2", parent: "root", data: { kind: "frame" as MyKind } },
        { id: "n3", parent: "n1", data: { kind: "button" as MyKind } },
        { id: "n4", parent: "n1", data: { kind: "button" as MyKind } },
        { id: "n5", parent: "n2", data: { kind: "button" as MyKind } },
    ];
    let nodeLookup = treeData.reduce((acc, cur) => { acc[cur.id] = toITree(cur); return acc; }, {} as Indexable<any>);
    function toITree<T>({ id, parent, data }: { id: string, parent: string | null, data: T }): ITree<T> {
        return { id, children: null, data };
    }
    let myTree = nodeLookup[treeData.shift()!.id];
    treeData.forEach((node) => {
        if (node.parent) {
            nodeLookup[node.parent!].children = nodeLookup[node.parent!].children || [];
            nodeLookup[node.parent!].children.push(nodeLookup[node.id]);
        }
    });
    return myTree;
}
let myTree = createTree();
var view = new SimpleTreeView({ id: "tree1", tree: myTree });
view.render(document.body);

// This change causes the crash
let n2 = myTree.children.pop()
myTree.children.unshift(n2);
view.render();
```

**Comment by WebReflection** [comment]
It'd be very helpful to have JS example so I can actually debug real code and exclude the transpiler caused issues.

I also don't use TS and I'd like to keep doing so. Thanks for helping out.

**Comment by WebReflection** [comment]
Btw, reading the code as is, it looks like you are doing few things a bit wrong:

  1. an element `children` is not an Array, you cannot push nodes
  2. you need to use lighterhtml to render stuff. If you do DOM operations by your own, you are messing up the library ownership of its content

In few words, I'd like to see the following:

  1. an example based in plain JS
  2. zero home-made changes on the tree, as that's not how lighterhtml works (or any of its similar projects)

Once these requirements are met, I can think about resolving a bug. Right now, there's nothing for me to work at, as techniques used in this example are both misleading and indirect due transpilation.

**Comment by AllNamesRTaken** [comment]
Here is a link to a code pen with JS code and the bug:
https://codepen.io/allnamesrtaken/pen/KKKBvZE

I am not doing manual html manipulations. I am only pushing and manipulating the tree data structure. All the rendering is done using lighterhtml.

**Comment by WebReflection** [comment]
Thanks, I'll have a look this evening or tomorrow early morning (GMT+01). 👋

**Comment by WebReflection** [comment]
@AllNamesRTaken if you use this import instead:

```js
import { html, render } from "https://unpkg.com/holedhtml?module";
```

everything seems to work as expected, could you confirm?

I've basically refactored the hell out of `lighterhtml` for this reason, and many mores ... please let me know how that works, so that I'll be more confident in publishing version 2.

**Comment by WebReflection** [comment]
**v2 is out**, so if you use `import { html, render } from "https://unpkg.com/lighterhtml?module";` instead of pika thing, you'll see no errors.

I am going to close this, as the whole logic changed, and I believe all old possible issues have been resolved.

Please let me know if that's not the case, thanks.

**Comment by AllNamesRTaken** [comment]
Yes you are right it works. I was reporting this at the same day it was fixed and npm might not have updated. Now there is a 2.0.1 version and it works. Thanks.
