### ISSUE TITLE
v2 Breaks Example

### ISSUE THREAD

**Issue by davidmerrique** [WebReflection/lighterhtml#73]
This example is broken https://codepen.io/WebReflection/pen/MZxYVm?editors=0010

Specifically this line:
```javascript
this.render = render.bind(this, shadow(this), this.render);
```
It works if I change it to this:
```javascript
this.render = render.bind(this, shadow(this), this.render.bind(this));
```
Thanks!

**Comment by WebReflection** [comment]
Thanks. I think there might be various examples breaking with V2. If you find others, please let me know in this issue, thanks a lot!
