### ISSUE TITLE
react-spring like library for lighterhtml

### ISSUE THREAD

**Issue by aFarkas** [WebReflection/lighterhtml#81]
Are there any a react-spring like libs that can be used for lighterhtml or do you have some plan to do this ;-).

**Comment by WebReflection** [comment]
interesting library I wasn't aware of, too bad it's coupled with React so ... the TL;DR answer is: nope, haven't planned it, but it looks like _neverland_ or _heresy_ would benefit from it, although it also looks like quite huge so ... not sure I'll find the time for that.

Hint for whoever would like to try: if an attribute contains a callback, as in `data-spring=${callback}` or `data-animation=${callback}`, the `callback` will receive the node, and any kind of sorcery could be done with that node right away.

**Comment by joshgillies** [comment]
`react-spring` is a relatively large and very react oriented animation framework, and as such mirroring functionality would require a fair amount of effort to rebuild in such a way to enable use with `lighterhtml`, et al.

However, if you're using hooks there exists a way to leverage hooks developed originally for Raact with both `dom-augmentor` and `augmentor`.

A caveat, and something to keep in mind if you're looking to go down this path is that any hook requiring or leveraging internal React functionality eg. `react-dom` will not work. `react-srping` is unfortunately one such library.

With that in mind, if your application is bundled by one of webpack, parcel, etc you can leverage the `package.json` field `alias` to remap `react` to `dom-augmentor`!

An example app leveraging the above to combine `lighterhtml`, `dom-augmentor` and `react-use` with it's `useSpring` hook is available here: https://codesandbox.io/s/lighterhtml-ract-use-spring-bs4pk
