### ISSUE TITLE
Breaking change in 2.0.10 ?

### ISSUE THREAD

**Issue by millette** [WebReflection/lighterhtml#82]
Hi,

I just upgraded to 2.0.10 and renaming `Hole` broke neverland. Or did I miss something?

P.S.: I just started with neverland/lighterhtml and I appreciate the experience so far, thanks!

**Comment by WebReflection** [comment]
uhm ... a rename should've not broken anything, but I'm on it, and apologies for the issue

**Comment by millette** [comment]
I'm also testing out parcel 2 (beta) and rollup at the same time. But reverting to 2.0.9 fixed my issue.

**Comment by millette** [comment]
If it turns out to be a breaking change, could you deprecate 2.0.10 and publish a 2.0.11 (same as 2.0.9, basically) + a 3.0.0 version with the rename? I think this should be the way to move forward.

**Comment by WebReflection** [comment]
is 2.0.11 ok? I've just published it

**Comment by WebReflection** [comment]
I'm super sorry, I was sure Hole was a direct export, and I've messed up. Thank you so much for filing this right away, so I could revert the change right away.

**Comment by millette** [comment]
Yes, just tested and it's all good now. Thanks for the quick response!

**Comment by WebReflection** [comment]
No, thank you!

**Comment by WebReflection** [comment]
P.S.

```
npm deprecate lighterhtml@2.0.10 'I have messed up a rename'
```

so not 2.0.10 is properly deprecated 👋

**Comment by millette** [comment]
Indeed https://www.npmjs.com/package/lighterhtml/v/2.0.10
