### ISSUE TITLE
Import components from external JS files?

### ISSUE THREAD

**Issue by ethanpil** [WebReflection/lighterhtml#85]
Can I do things like `import TodoList from './TodoList'` to load `TodoList.js` as a new components in lighterhtml and uhtml? (like is done in react to build components)

I dont see this in any of the examples.

**Comment by yuretz** [comment]
Of course you can, but I don't think this is a special lighterhtml/uhtml feature. This is how you import stuff from modules in modern JavaScript, so if your `TodoList.js` module has something like
```javascript
import {html} from 'lighterhtml';
export default function TodoList() { return html`<ul>...</ul>`; }
``` 
then you should be good.

**Comment by WebReflection** [comment]
see [neverland](https://github.com/WebReflection/neverland/#readme) or [heresy](https://github.com/WebReflection/heresy/#readme), both based on _lighterhtml_ 👋
