### ISSUE TITLE
How to pass async data into render()?

### ISSUE THREAD

**Issue by winston0410** [WebReflection/lighterhtml#96]
Hi,

How can I pass async data into the callback function of render()?  I tried will the following code but it didn't work.  I suspect that that second callback is not designed to be an async function.  When I set it as async, it returns:
```
lighterhtml.js:1 Uncaught (in promise) TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.
```

My code: 

```
 //userProfile is the data generated by other async function

  render(document.body, async (userProfile) => {
    await console.log(userProfile); //Return undefinded;
    return html`<div></div>`;
  });
```

**Comment by WebReflection** [comment]
it's not compatible with async 'cause it would slow down everything on the sync path, but you can either use an async update helper, or see how iHN solved the issue https://github.com/WebReflection/hn/blob/master/client/%40/js/app.js#L127-L157

```js
const update = async (userProfile) => {
  const value = await userProfile;
  render(document.body,  html`<div>${value}</div>`);
};
```

**Comment by winston0410** [comment]
Thank you it worked!
