### ISSUE TITLE
Workaround for DOMparseing inside a lighterHTML componant.

### ISSUE THREAD

**Issue by winston0410** [WebReflection/lighterhtml#97]
I have created a component with lighterHTML, and I want it to be reusable to the point that I can use a variable as its tag name.

```
const DisplayName = (userProfile, tag="h3") => {
  let parser = new DOMParser();
  tag = parser.parseFromString(tag, 'text/html')

  return html `
  <${tag}>${userProfile.displayName} </${tag}>
`
};
```

But this returns `Uncaught (in promise) DOMException: Failed to execute 'insertBefore' on 'Node': Nodes of type '#document' may not be inserted inside nodes of type '#document-fragment'.`

How can I achieve this without breaking lighterHTML(I am sure this is related with how lighterHTML works, but I am not sure I understand it well enough)?

Btw I am still experimenting with lighterHTML and I really love it.  I guess it has a great potential to work with JAMStack site!  Great work!

**Comment by WebReflection** [comment]
this is a recurrent question and the answer is always the same: it cannot possibly work like that.

https://github.com/WebReflection/uhtml/issues/15#issuecomment-643748279

**Comment by WebReflection** [comment]
btw, I think I might have a solution to this

**Comment by WebReflection** [comment]
@winston0410 as this is the 12th time somebody asks me that, I've now made it possible:
https://github.com/WebReflection/static-params#readme

Please read carefully the whole README.

P.S. You cannot pass a node, but you can pass a tag name

**Comment by winston0410** [comment]
This is really awesome.  I am going to try it now.  LighterHTML and your works deserve more attentions!
