### ISSUE TITLE
Cannot test lighterhtml with Jasmine

### ISSUE THREAD

**Issue by winston0410** [WebReflection/lighterhtml#98]
I am trying test my project built with Lighterhtml with Jasmine, but it is returning `document undefined`.  I guess this problem can be solved by adding something `jsdom` to it.  Is there a better approach for this, without increasing the size of Lighterhtml?

My project built with lighterhtml: https://github.com/winston0410/freedom-editor-lighterhtml-paragraph-block

My Jasmine test code:

```
const { Paragraph } = require('../src/index.js')

describe('Test block essential functionalities', () => {

  const paragraphBlock = new Paragraph()

  const i18n = {
    locale: 'en-US',
    rtl: 'auto'
  }

  it('should return an node without data with render()', () => {
    expect(paragraphBlock.render(i18n)).toHaveClass('freedom-editor-blocks')
  })

  /* it('should return an node with data with render()', () => {

  })

  it('should save content of a node with save()', () => {

  }) */
})
```

**Comment by WebReflection** [comment]
meet [basicHTML](https://github.com/WebReflection/basicHTML#readme), which is what I use to test every FE library of mine 👋

**Comment by winston0410** [comment]
I see.  Thanks!

**Comment by winston0410** [comment]
For someone who needs to test Lighterhtml, you can use jsdom or basicHTML.  I didn't try basicHTML in the end.  Hope this code would help, I am testing it with Jasmine.

```

const jsdom = require('jsdom')
const { JSDOM } = jsdom
const dom = new JSDOM('<html><body></body></html>')

global.document = dom.window.document
global.window = dom.window
global.navigator = dom.window.navigator

//Files that using lighterhtml
const { Heading } = require('../src/index.js')

describe('Test block essential functionalities:', () => {
  const headingBlock = new Heading()
//More code

```

**Comment by WebReflection** [comment]
with _basicHTML_ it's:

```js
require('basichtml').init();
```

that's it

**Comment by winston0410** [comment]
> with _basicHTML_ it's:
> 
> ```js
> require('basichtml').init();
> ```
> 
> that's it

What? I though I had to rewrite my lighterhtml code in basicHTML.  That's awesome!

**Comment by WebReflection** [comment]
I should've linked a better example, apologies:

https://github.com/WebReflection/basicHTML#new-init-in-013

**Comment by WebReflection** [comment]
P.S.2 this is how I test uhtml https://github.com/WebReflection/uhtml/blob/master/test/coverage.js#L1

**Comment by winston0410** [comment]
Tried basicHTML.  Brilliant!

https://github.com/winston0410/freedom-editor-lighterhtml-code-block/commit/41ad325ff6e3c2c92df409d2a1b00b02bba2f5c3
